version: '3.7'

services:
    postgres:
        restart: always
        image: "postgres:latest"
        env_file:
            - prod2lab.env
    web:
        build: .
        restart: always
        command: bash -c "cd /opt/prod2lab/ && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
        env_file:
            - prod2lab.env
        ports:
            - "127.0.0.1:8000:8000"
        depends_on:
            - postgres
    rabbitmq:
        image: "rabbitmq:3"
        restart: always
        env_file:
            - prod2lab.env
    worker:
        build: .
        restart: always
        command: bash -c "cd /opt/prod2lab/ && celery -A prod2app worker -l info"
        env_file:
            - prod2lab.env
        depends_on:
            - rabbitmq
